import type { EarthquakeEvent, SourceHealth } from "@/lib/types/earthquake";

// Données de démonstration réalistes (coordonnées et localités réelles),
// magnitudes/horodatages simulés en attendant la connexion aux flux temps réel.

type Seed = Omit<EarthquakeEvent, "id" | "confidence" | "confidenceScore"> & {
  confidence?: EarthquakeEvent["confidence"];
};

function confidenceFor(score: number): EarthquakeEvent["confidence"] {
  if (score >= 0.85) return "verified";
  if (score >= 0.6) return "likely";
  return "unconfirmed";
}

function build(seeds: Seed[]): EarthquakeEvent[] {
  return seeds.map((seed, index) => {
    const confidenceScore = Math.min(
      0.99,
      0.55 + seed.magnitude / 12 + (seed.source === "USGS" || seed.source === "EMSC" ? 0.08 : 0),
    );
    return {
      ...seed,
      id: `pc-${seed.source.toLowerCase()}-${index}-${seed.externalId}`,
      confidence: seed.confidence ?? confidenceFor(confidenceScore),
      confidenceScore: Number(confidenceScore.toFixed(2)),
    };
  });
}

const NOW = new Date("2026-07-02T14:00:00Z");
function hoursAgo(h: number) {
  return new Date(NOW.getTime() - h * 3600 * 1000).toISOString();
}
function daysAgo(d: number) {
  return new Date(NOW.getTime() - d * 24 * 3600 * 1000).toISOString();
}
function yearsAgo(y: number, monthDay = "01-15T10:00:00Z") {
  return new Date(NOW.getFullYear() - y, 0, 1).toISOString().slice(0, 4) + `-${monthDay}`;
}

export const caribbeanEarthquakes: EarthquakeEvent[] = build([
  {
    externalId: "us7000pcar",
    magnitude: 5.8,
    magnitudeType: "Mw",
    depthKm: 12,
    place: "18 km au sud-ouest de Port-au-Prince",
    city: "Port-au-Prince",
    country: "Haïti",
    countryCode: "HT",
    latitude: 18.4247,
    longitude: -72.6764,
    timeUtc: hoursAgo(2),
    source: "USGS",
    felt: 412,
    tsunamiRisk: false,
    region: "caribbean",
  },
  {
    externalId: "emsc650912",
    magnitude: 4.6,
    magnitudeType: "Mb",
    depthKm: 35,
    place: "22 km au nord-est de Les Cayes",
    city: "Les Cayes",
    country: "Haïti",
    countryCode: "HT",
    latitude: 18.3167,
    longitude: -73.55,
    timeUtc: hoursAgo(9),
    source: "EMSC",
    felt: 87,
    tsunamiRisk: false,
    region: "caribbean",
  },
  {
    externalId: "ipgp-gpe-0231",
    magnitude: 3.9,
    magnitudeType: "Ml",
    depthKm: 8,
    place: "12 km au sud-est de Pointe-à-Pitre",
    city: "Pointe-à-Pitre",
    country: "Guadeloupe",
    countryCode: "GP",
    latitude: 16.15,
    longitude: -61.5,
    timeUtc: hoursAgo(14),
    source: "IPGP",
    felt: 34,
    tsunamiRisk: false,
    region: "caribbean",
  },
  {
    externalId: "ipgp-mtq-0118",
    magnitude: 3.2,
    magnitudeType: "Ml",
    depthKm: 22,
    place: "9 km au nord de Fort-de-France",
    city: "Fort-de-France",
    country: "Martinique",
    countryCode: "MQ",
    latitude: 14.65,
    longitude: -61.02,
    timeUtc: hoursAgo(20),
    source: "IPGP",
    felt: 11,
    tsunamiRisk: false,
    region: "caribbean",
  },
  {
    externalId: "us7000pbz1",
    magnitude: 4.3,
    magnitudeType: "Mb",
    depthKm: 68,
    place: "30 km au nord de Santo Domingo",
    city: "Santo Domingo",
    country: "République dominicaine",
    countryCode: "DO",
    latitude: 18.75,
    longitude: -69.9,
    timeUtc: hoursAgo(27),
    source: "USGS",
    felt: 56,
    tsunamiRisk: false,
    region: "caribbean",
  },
  {
    externalId: "fdsn-pr-9982",
    magnitude: 4.9,
    magnitudeType: "Mw",
    depthKm: 10,
    place: "8 km au sud de Ponce",
    city: "Ponce",
    country: "Porto Rico",
    countryCode: "PR",
    latitude: 17.9,
    longitude: -66.61,
    timeUtc: hoursAgo(31),
    source: "FDSN",
    felt: 198,
    tsunamiRisk: false,
    region: "caribbean",
  },
  {
    externalId: "us7000pby5",
    magnitude: 3.6,
    magnitudeType: "Ml",
    depthKm: 15,
    place: "16 km à l'est de Kingston",
    city: "Kingston",
    country: "Jamaïque",
    countryCode: "JM",
    latitude: 17.97,
    longitude: -76.6,
    timeUtc: daysAgo(2),
    source: "USGS",
    felt: 22,
    tsunamiRisk: false,
    region: "caribbean",
  },
  {
    externalId: "emsc650744",
    magnitude: 5.1,
    magnitudeType: "Mw",
    depthKm: 45,
    place: "40 km au nord-est de Basseterre",
    city: "Basseterre",
    country: "Saint-Christophe-et-Niévès",
    countryCode: "KN",
    latitude: 17.5,
    longitude: -62.6,
    timeUtc: daysAgo(3),
    source: "EMSC",
    felt: 63,
    tsunamiRisk: false,
    region: "caribbean",
  },
  {
    externalId: "us7000pbv2",
    magnitude: 4.1,
    magnitudeType: "Mb",
    depthKm: 55,
    place: "25 km au sud-ouest de Roseau",
    city: "Roseau",
    country: "Dominique",
    countryCode: "DM",
    latitude: 15.25,
    longitude: -61.45,
    timeUtc: daysAgo(4),
    source: "USGS",
    felt: 19,
    tsunamiRisk: false,
    region: "caribbean",
  },
  {
    externalId: "ipgp-mtq-0099",
    magnitude: 3.4,
    magnitudeType: "Ml",
    depthKm: 30,
    place: "14 km au large du Marin",
    city: "Le Marin",
    country: "Martinique",
    countryCode: "MQ",
    latitude: 14.42,
    longitude: -60.7,
    timeUtc: daysAgo(5),
    source: "IPGP",
    felt: 8,
    tsunamiRisk: false,
    region: "caribbean",
  },
  {
    externalId: "fdsn-vg-2211",
    magnitude: 4.4,
    magnitudeType: "Ml",
    depthKm: 40,
    place: "18 km au nord-ouest de Kingstown",
    city: "Kingstown",
    country: "Saint-Vincent-et-les-Grenadines",
    countryCode: "VC",
    latitude: 13.25,
    longitude: -61.35,
    timeUtc: daysAgo(6),
    source: "FDSN",
    felt: 27,
    tsunamiRisk: false,
    region: "caribbean",
  },
  {
    externalId: "us7000pbt8",
    magnitude: 5.4,
    magnitudeType: "Mw",
    depthKm: 60,
    place: "60 km au nord de Port of Spain",
    city: "Port of Spain",
    country: "Trinité-et-Tobago",
    countryCode: "TT",
    latitude: 11.4,
    longitude: -61.5,
    timeUtc: daysAgo(7),
    source: "USGS",
    felt: 134,
    tsunamiRisk: false,
    region: "caribbean",
  },
  {
    externalId: "emsc650601",
    magnitude: 3.7,
    magnitudeType: "Ml",
    depthKm: 18,
    place: "10 km au sud de Bridgetown",
    city: "Bridgetown",
    country: "Barbade",
    countryCode: "BB",
    latitude: 13.0,
    longitude: -59.6,
    timeUtc: daysAgo(9),
    source: "EMSC",
    felt: 14,
    tsunamiRisk: false,
    region: "caribbean",
  },
  {
    externalId: "us7000pbr4",
    magnitude: 4.7,
    magnitudeType: "Mb",
    depthKm: 25,
    place: "35 km au sud-est de Santiago de Cuba",
    city: "Santiago de Cuba",
    country: "Cuba",
    countryCode: "CU",
    latitude: 19.9,
    longitude: -75.6,
    timeUtc: daysAgo(11),
    source: "USGS",
    felt: 71,
    tsunamiRisk: false,
    region: "caribbean",
  },
  {
    externalId: "fdsn-bh-1187",
    magnitude: 3.9,
    magnitudeType: "Ml",
    depthKm: 12,
    place: "20 km à l'est de Nassau",
    city: "Nassau",
    country: "Bahamas",
    countryCode: "BS",
    latitude: 25.05,
    longitude: -77.2,
    timeUtc: daysAgo(13),
    source: "FDSN",
    felt: 5,
    tsunamiRisk: false,
    region: "caribbean",
  },
  {
    externalId: "us7000pbn9",
    magnitude: 6.2,
    magnitudeType: "Mw",
    depthKm: 15,
    place: "24 km au nord-ouest de Les Cayes",
    city: "Les Cayes",
    country: "Haïti",
    countryCode: "HT",
    latitude: 18.35,
    longitude: -73.85,
    timeUtc: daysAgo(18),
    source: "USGS",
    felt: 892,
    tsunamiRisk: true,
    region: "caribbean",
  },
  {
    externalId: "ipgp-gpe-0177",
    magnitude: 3.1,
    magnitudeType: "Ml",
    depthKm: 6,
    place: "5 km au nord de Basse-Terre",
    city: "Basse-Terre",
    country: "Guadeloupe",
    countryCode: "GP",
    latitude: 16.02,
    longitude: -61.72,
    timeUtc: daysAgo(20),
    source: "IPGP",
    felt: 9,
    tsunamiRisk: false,
    region: "caribbean",
  },
  {
    externalId: "fdsn-gd-3345",
    magnitude: 4.8,
    magnitudeType: "Mw",
    depthKm: 33,
    place: "28 km au sud-ouest de Saint-Georges",
    city: "Saint-Georges",
    country: "Grenade",
    countryCode: "GD",
    latitude: 11.9,
    longitude: -61.9,
    timeUtc: daysAgo(23),
    source: "FDSN",
    felt: 41,
    tsunamiRisk: false,
    region: "caribbean",
  },
  {
    externalId: "us7000pbk3",
    magnitude: 4.0,
    magnitudeType: "Mb",
    depthKm: 48,
    place: "15 km au nord de Castries",
    city: "Castries",
    country: "Sainte-Lucie",
    countryCode: "LC",
    latitude: 14.15,
    longitude: -61.0,
    timeUtc: daysAgo(26),
    source: "USGS",
    felt: 17,
    tsunamiRisk: false,
    region: "caribbean",
  },
  {
    externalId: "emsc650388",
    magnitude: 3.5,
    magnitudeType: "Ml",
    depthKm: 10,
    place: "11 km au sud-est de Saint-Jean",
    city: "Saint-Jean",
    country: "Antigua-et-Barbuda",
    countryCode: "AG",
    latitude: 17.05,
    longitude: -61.75,
    timeUtc: daysAgo(29),
    source: "EMSC",
    felt: 6,
    tsunamiRisk: false,
    region: "caribbean",
  },
  {
    externalId: "us7000pbg7",
    magnitude: 5.0,
    magnitudeType: "Mw",
    depthKm: 20,
    place: "12 km au sud-ouest de Charlotte Amalie",
    city: "Charlotte Amalie",
    country: "Îles Vierges des États-Unis",
    countryCode: "VI",
    latitude: 18.3,
    longitude: -64.98,
    timeUtc: daysAgo(34),
    source: "USGS",
    felt: 103,
    tsunamiRisk: false,
    region: "caribbean",
  },
  {
    externalId: "fdsn-pr-8871",
    magnitude: 5.6,
    magnitudeType: "Mw",
    depthKm: 9,
    place: "6 km au sud-est de Guánica",
    city: "Guánica",
    country: "Porto Rico",
    countryCode: "PR",
    latitude: 17.95,
    longitude: -66.9,
    timeUtc: daysAgo(41),
    source: "FDSN",
    felt: 356,
    tsunamiRisk: false,
    region: "caribbean",
  },
  {
    externalId: "us7000pba2",
    magnitude: 3.8,
    magnitudeType: "Ml",
    depthKm: 14,
    place: "9 km au nord de Willemstad",
    city: "Willemstad",
    country: "Curaçao",
    countryCode: "CW",
    latitude: 12.15,
    longitude: -68.95,
    timeUtc: daysAgo(48),
    source: "USGS",
    felt: 13,
    tsunamiRisk: false,
    region: "caribbean",
  },
  {
    externalId: "ipgp-mtq-0034",
    magnitude: 4.2,
    magnitudeType: "Ml",
    depthKm: 28,
    place: "20 km à l'est de Le Vauclin",
    city: "Le Vauclin",
    country: "Martinique",
    countryCode: "MQ",
    latitude: 14.55,
    longitude: -60.75,
    timeUtc: daysAgo(55),
    source: "IPGP",
    felt: 24,
    tsunamiRisk: false,
    region: "caribbean",
  },
  {
    externalId: "us7000pb61",
    magnitude: 4.5,
    magnitudeType: "Mb",
    depthKm: 62,
    place: "50 km au nord-est de Oranjestad",
    city: "Oranjestad",
    country: "Aruba",
    countryCode: "AW",
    latitude: 12.6,
    longitude: -69.9,
    timeUtc: daysAgo(63),
    source: "USGS",
    felt: 15,
    tsunamiRisk: false,
    region: "caribbean",
  },
  {
    externalId: "emsc649902",
    magnitude: 5.3,
    magnitudeType: "Mw",
    depthKm: 38,
    place: "45 km au nord de Cap-Haïtien",
    city: "Cap-Haïtien",
    country: "Haïti",
    countryCode: "HT",
    latitude: 20.1,
    longitude: -72.2,
    timeUtc: daysAgo(72),
    source: "EMSC",
    felt: 176,
    tsunamiRisk: false,
    region: "caribbean",
  },
  {
    externalId: "us7000pb2c",
    magnitude: 6.4,
    magnitudeType: "Mw",
    depthKm: 10,
    place: "5 km au sud-est de Guánica",
    city: "Guánica",
    country: "Porto Rico",
    countryCode: "PR",
    latitude: 17.9,
    longitude: -66.85,
    timeUtc: daysAgo(120),
    source: "USGS",
    felt: 1240,
    tsunamiRisk: true,
    region: "caribbean",
  },
  {
    externalId: "us2010haiti",
    magnitude: 7.0,
    magnitudeType: "Mw",
    depthKm: 13,
    place: "25 km au sud-ouest de Port-au-Prince",
    city: "Port-au-Prince",
    country: "Haïti",
    countryCode: "HT",
    latitude: 18.457,
    longitude: -72.533,
    timeUtc: "2010-01-12T21:53:10Z",
    source: "USGS",
    felt: 3200000,
    tsunamiRisk: true,
    region: "caribbean",
    confidence: "verified",
  },
  {
    externalId: "us2021haiti",
    magnitude: 7.2,
    magnitudeType: "Mw",
    depthKm: 10,
    place: "8 km au nord-est de Saint-Louis-du-Sud",
    city: "Les Cayes",
    country: "Haïti",
    countryCode: "HT",
    latitude: 18.4,
    longitude: -73.48,
    timeUtc: "2021-08-14T12:29:08Z",
    source: "USGS",
    felt: 890000,
    tsunamiRisk: true,
    region: "caribbean",
    confidence: "verified",
  },
  {
    externalId: "us2020puertorico",
    magnitude: 6.4,
    magnitudeType: "Mw",
    depthKm: 10,
    place: "8 km au sud de Indios",
    city: "Ponce",
    country: "Porto Rico",
    countryCode: "PR",
    latitude: 17.916,
    longitude: -66.813,
    timeUtc: "2020-01-07T08:24:26Z",
    source: "USGS",
    felt: 154000,
    tsunamiRisk: false,
    region: "caribbean",
    confidence: "verified",
  },
  {
    externalId: "us1946dr",
    magnitude: 8.0,
    magnitudeType: "Mw",
    depthKm: 25,
    place: "Baie de Samaná",
    city: "Samaná",
    country: "République dominicaine",
    countryCode: "DO",
    latitude: 19.71,
    longitude: -69.29,
    timeUtc: yearsAgo(80, "08-04T17:51:00Z"),
    source: "USGS",
    felt: 50000,
    tsunamiRisk: true,
    region: "caribbean",
    confidence: "verified",
  },
]);

const globalExtras: EarthquakeEvent[] = build([
  {
    externalId: "us7000ptky",
    magnitude: 6.7,
    magnitudeType: "Mw",
    depthKm: 18,
    place: "30 km à l'est d'Antakya",
    city: "Antakya",
    country: "Turquie",
    countryCode: "TR",
    latitude: 36.2,
    longitude: 36.4,
    timeUtc: daysAgo(3),
    source: "EMSC",
    felt: 5400,
    tsunamiRisk: false,
    region: "global",
  },
  {
    externalId: "us7000ptjp",
    magnitude: 6.1,
    magnitudeType: "Mw",
    depthKm: 45,
    place: "60 km à l'est de Sendai",
    city: "Sendai",
    country: "Japon",
    countryCode: "JP",
    latitude: 38.26,
    longitude: 141.9,
    timeUtc: daysAgo(5),
    source: "USGS",
    felt: 3200,
    tsunamiRisk: true,
    region: "global",
  },
  {
    externalId: "us7000ptid",
    magnitude: 5.9,
    magnitudeType: "Mw",
    depthKm: 90,
    place: "70 km au nord-ouest de Manado",
    city: "Manado",
    country: "Indonésie",
    countryCode: "ID",
    latitude: 1.6,
    longitude: 124.4,
    timeUtc: daysAgo(8),
    source: "USGS",
    felt: 1100,
    tsunamiRisk: false,
    region: "global",
  },
  {
    externalId: "us7000ptcl",
    magnitude: 6.5,
    magnitudeType: "Mw",
    depthKm: 35,
    place: "40 km au large de Valparaíso",
    city: "Valparaíso",
    country: "Chili",
    countryCode: "CL",
    latitude: -33.05,
    longitude: -71.9,
    timeUtc: daysAgo(12),
    source: "USGS",
    felt: 2600,
    tsunamiRisk: true,
    region: "global",
  },
  {
    externalId: "us7000ptmx",
    magnitude: 5.7,
    magnitudeType: "Mw",
    depthKm: 60,
    place: "25 km au sud d'Acapulco",
    city: "Acapulco",
    country: "Mexique",
    countryCode: "MX",
    latitude: 16.7,
    longitude: -99.8,
    timeUtc: daysAgo(15),
    source: "USGS",
    felt: 1780,
    tsunamiRisk: false,
    region: "global",
  },
  {
    externalId: "us7000ptgr",
    magnitude: 5.2,
    magnitudeType: "Mw",
    depthKm: 10,
    place: "20 km au sud de Kalamata",
    city: "Kalamata",
    country: "Grèce",
    countryCode: "GR",
    latitude: 36.9,
    longitude: 22.1,
    timeUtc: daysAgo(19),
    source: "EMSC",
    felt: 640,
    tsunamiRisk: false,
    region: "global",
  },
  {
    externalId: "us7000ptph",
    magnitude: 6.0,
    magnitudeType: "Mw",
    depthKm: 28,
    place: "50 km au nord-est de Davao",
    city: "Davao",
    country: "Philippines",
    countryCode: "PH",
    latitude: 7.5,
    longitude: 125.9,
    timeUtc: daysAgo(24),
    source: "USGS",
    felt: 980,
    tsunamiRisk: false,
    region: "global",
  },
  {
    externalId: "us7000ptca",
    magnitude: 4.9,
    magnitudeType: "Mw",
    depthKm: 12,
    place: "15 km au nord-est de San Francisco",
    city: "San Francisco",
    country: "États-Unis",
    countryCode: "US",
    latitude: 37.9,
    longitude: -122.2,
    timeUtc: daysAgo(28),
    source: "USGS",
    felt: 2100,
    tsunamiRisk: false,
    region: "global",
  },
]);

export const allEarthquakes: EarthquakeEvent[] = [...caribbeanEarthquakes, ...globalExtras].sort(
  (a, b) => new Date(b.timeUtc).getTime() - new Date(a.timeUtc).getTime(),
);

export const sourcesHealth: SourceHealth[] = [
  {
    code: "USGS",
    name: "USGS",
    description: "United States Geological Survey — Earthquake Hazards Program",
    status: "operational",
    latencySeconds: 42,
    lastSyncUtc: hoursAgo(0.05),
    region: "Mondial",
  },
  {
    code: "EMSC",
    name: "EMSC",
    description: "European-Mediterranean Seismological Centre",
    status: "operational",
    latencySeconds: 38,
    lastSyncUtc: hoursAgo(0.08),
    region: "Europe / Méditerranée / Mondial",
  },
  {
    code: "IPGP",
    name: "IPGP",
    description: "Institut de Physique du Globe de Paris — Réseau Antilles",
    status: "operational",
    latencySeconds: 55,
    lastSyncUtc: hoursAgo(0.12),
    region: "Antilles françaises",
  },
  {
    code: "FDSN",
    name: "FDSN",
    description: "International Federation of Digital Seismograph Networks",
    status: "degraded",
    latencySeconds: 210,
    lastSyncUtc: hoursAgo(1.4),
    region: "Réseau international",
  },
];

export function magnitudeTier(magnitude: number): "low" | "moderate" | "high" | "severe" {
  if (magnitude < 3.5) return "low";
  if (magnitude < 4.5) return "moderate";
  if (magnitude < 6) return "high";
  return "severe";
}

export const caribbeanCountries = Array.from(
  new Set(caribbeanEarthquakes.map((e) => e.country)),
).sort();
